@BetaCycle_HostAddress = http://localhost:5270

GET {{BetaCycle_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{BetaCycle_HostAddress}}/api/Users
Accept: application/json

###

POST {{BetaCycle_HostAddress}}/api/Users
Accept: application/json

{
    "fullName": "string",
    "birthDate": "2021-07-12",
    "phone": "string",
    "security": 0
}
